version: '3'
services:
    nginx:
        ports: 
            - "80:80"
        image: nginx
        volumes: 
            - "./frontend:/usr/share/nginx/html:ro"
        depends_on:
            - "node"

    mongo:
        ports:
            - "27017:27017"
        volumes:
            - "/home/jjj/mongoData:/data/db"
        image: mongo

    node:
        build: .
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "3000:3000"
        depends_on:
            - "mongo"
