version: '3'
services:
    nginx:
        ports: 
            - "80:80"
            - "443:443"
        image: nginx
        volumes: 
            - "./frontend:/usr/share/nginx/html:ro"
            - "./https:/etc/nginx/ssl"
            - "./default.conf:/etc/nginx/conf.d/default.conf"
        environment:
            - TZ=Asia/Taipei
        depends_on:
            - "node"

    mongo:
        ports:
            - "27017:27017"
        volumes:
            - "/home/jjj/mongoData:/data/db"
        environment:
            - TZ=Asia/Taipei
        image: mongo

    node:
        build: .
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
            - "./https:/https"
        environment:
            - TZ=Asia/Taipei
        ports:
            - "3000:3000"
        depends_on:
            - "mongo"
