version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    docker:
        - image: cimg/node:13.11.0
    steps:
        - node/test:
            version: 14.15.1
        - store_test_results:
            path: test-results


workflows:
  node-tests:
    jobs:
        - test
