version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - run:
          command: export COVERALLS_REPO_TOKEN=Cfv7OXRCkb6mGP5Y1gmtrFZfiyB16wTMD
      - checkout
      - node/install-packages
      - run:
          command: ./node_modules/jest/bin/jest.js --config=test/jest.config.js && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
      - store_artifacts:
          path: coverage

workflows:
  node-tests:
    jobs:
        - test
